[package]
name = "sodigy-optimize"
version = "0.1.0"
edition = "2024"

[dependencies]
sodigy-bytecode = { version = "0.1.0", path = "../bytecode" }
sodigy-mir = { version = "0.1.0", path = "../mir" }
